# Generated by Django 5.0.6 on 2024-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Личность', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AddField(
            model_name='human',
            name='ismale',
            field=models.BooleanField(default=True),
        ),
    ]
