# Generated by Django 5.0.6 on 2024-05-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0002_alter_human_options_human_ismale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Human',
            new_name='Humans',
        ),
        migrations.AlterModelOptions(
            name='humans',
            options={'ordering': ['famil', 'name', 'otches'], 'verbose_name': 'Личность', 'verbose_name_plural': 'Люди'},
        ),
    ]
