# Generated by Django 5.0.6 on 2024-05-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0003_rename_human_humans_alter_humans_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='humans',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='famil',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='ismale',
            field=models.BooleanField(default=True, verbose_name='Мужчина'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='nicname',
            field=models.CharField(max_length=50, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='otches',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='humans',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='humans.professions', verbose_name='Профессия'),
        ),
    ]
